### ISSUE TITLE
Version for Cud?

### ISSUE THREAD

**Issue by Alexey-T** [GCTsalamagkakis/Romanize#1]
Hi,
it's first plugin for roman numbers, seems. Good. Can you make version for CudaText too?
http://wiki.freepascal.org/CudaText_API
Or should i make it?

**Comment by GCTsalamagkakis** [comment]
Hello,

i will check it out and i will inform you very soon about it, does that
sound good?

Thanks for reaching out

**Comment by Alexey-T** [comment]
Ok, I have made this plugin, will publish soon. I used your code of Roman num converter. 

If you split funcs to_romans, from_romans to module, will be good, I can sync with you

**Comment by GCTsalamagkakis** [comment]
Sorry, can you explain? Do you mean you want them in separate files?

**Comment by Alexey-T** [comment]
Yes, these two functions in separate py file

**Comment by GCTsalamagkakis** [comment]
alright, i put them both on romans.py, as well as the sepcial characters
list that was needed

**Comment by Alexey-T** [comment]
Thanks..
