### ISSUE TITLE
Use romans.py

### ISSUE THREAD

**Issue by Alexey-T** [GCTsalamagkakis/Romanize#2]
Can you use new file in plugin?

from .romans import *

**Comment by GCTsalamagkakis** [comment]
in the sublime one?

**Comment by GCTsalamagkakis** [comment]
done

**Comment by Alexey-T** [comment]
thanks.

**Comment by GCTsalamagkakis** [comment]
are you going to sync today by the way?

**Comment by Alexey-T** [comment]
I will sync after you apply pull-request, is it ok?

**Comment by Alexey-T** [comment]
I have synced py file with you- https://github.com/CudaText-addons/cuda_romanize

**Comment by GCTsalamagkakis** [comment]
Alright, im really new to git so it takes me some time to figure out whats
going on etc, sorry
